<?php

namespace Database\Seeders;

use App\Models\User;

use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
// use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     */
    public function run(): void
    {
        DB::table('users')->insert([
          [
            'name' => 'ANGGA MEI DIANTO',
            'email' => 'anggameidianto@gmail.com',
            'password' => Hash::make('rahasia123'),
            'birth_place' => 'KEDIRI',
            'sex' => 'M',
            'birth_date' => '31/03/1997',
            'status' => 'Kontrak',
            'join_date' => '01/03/2024',
            'dept' => 'Depo Surabaya',
            'job_title' => 'Kepala Depo',
        ],
        [
            'name' => 'DADANG SETIAWAN',
            'email' => 'dadangsetiawan@gmail.com',
            'password' => Hash::make('rahasia123'),
            'birth_place' => 'SURABAYA',
            'sex' => 'M',
            'birth_date' => '25/11/1997',
            'status' => 'Tetap',
            'join_date' => '01/08/2023',
            'dept' => 'Marketing',
            'job_title' => 'Manager',
        ],
        [
            'name' => 'DANIEL TATO ALIK',
            'email' => 'danieltatoalik@gmail.com',
            'password' => Hash::make('rahasia123'),
            'birth_place' => 'SURABAYA',
            'sex' => 'M',
            'birth_date' => '19/05/1996',
            'status' => 'Tetap',
            'join_date' => '01/11/2019',
            'dept' => 'sales',
            'job_title' => 'Sales Rep',
        ],
        [
            'name' => 'RISKY SCORFANIE',
            'email' => 'riskyscorfanie@gmail.com',
            'password' => Hash::make('rahasia123'),
            'birth_place' => 'MALANG',
            'sex' => 'M',
            'birth_date' => '23/04/1998',
            'status' => 'Tetap',
            'join_date' => '06/01/2019',
            'dept' => 'sales',
            'job_title' => 'Supervisor',
        ],
        [
            'name' => 'RIZKY PRASTIKA',
            'email' => 'rizkyprastika@gmail.com',
            'password' => Hash::make('rahasia123'),
            'birth_place' => 'JEMBER',
            'sex' => 'M',
            'birth_date' => '24/04/1996',
            'status' => 'Tetap',
            'join_date' => '09/01/2023',
            'dept' => 'sales',
            'job_title' => 'Sales Rep',
        ],
        [
            'name' => 'SARAH HUSNUL KHOTIMAH',
            'email' => 'sarahhusnulkhotimah@gmail.com',
            'password' => Hash::make('rahasia123'),
            'birth_place' => 'BANYUWANGI',
            'sex' => 'F',
            'birth_date' => '26/10/1997',
            'status' => 'Tetap',
            'join_date' => '10/01/2021',
            'dept' => 'sales',
            'job_title' => 'Sales Rep',
        ],
        [
            'name' => 'DENDI SUPARDI IRAWAN',
            'email' => 'dendisupardiirawan@gmail.com',
            'password' => Hash::make('rahasia123'),
            'birth_place' => 'BANYUWANGI',
            'sex' => 'M',
            'birth_date' => '21/08/1997',
            'status' => 'Tetap',
            'join_date' => '09/08/2024',
            'dept' => 'sales',
            'job_title' => 'Sales Rep',
        ],
        [
            'name' => 'TIRA ASTRIYANI',
            'email' => 'tiraastriyani@gmail.com',
            'password' => Hash::make('rahasia123'),
            'birth_place' => 'BANYUWANGI',
            'sex' => 'F',
            'birth_date' => '07/07/1996',
            'status' => 'Tetap',
            'join_date' => '18/03/2024',
            'dept' => 'sales',
            'job_title' => 'Sales Rep',
        ],
        [
            'name' => 'HARDINTIA W.S',
            'email' => 'hardintiaws@gmail.com',
            'password' => Hash::make('rahasia123'),
            'birth_place' => 'BANYUWANGI',
            'sex' => 'M',
            'birth_date' => '25/02/1998',
            'status' => 'Tetap',
            'join_date' => '01/09/2017',
            'dept' => 'sales',
            'job_title' => 'Sales Rep',
        ],
        [
            'name' => 'DEDE SUHENDRI',
            'email' => 'dedesuhendri@gmail.com',
            'password' => Hash::make('rahasia123'),
            'birth_place' => 'SIDOARJO',
            'sex' => 'M',
            'birth_date' => '14/05/1998',
            'status' => 'Tetap',
            'join_date' => '01/09/2017',
            'dept' => 'Pengiriman',
            'job_title' => 'Driver',
        ],
        [
            'name' => 'RIAN PRASETYO',
            'email' => 'rianprasetyo@gmail.com',
            'password' => Hash::make('rahasia123'),
            'birth_place' => 'SURABAYA',
            'sex' => 'M',
            'birth_date' => '16/05/1995',
            'status' => 'Tetap',
            'join_date' => '04/09/2017',
            'dept' => 'Pengiriman',
            'job_title' => 'Driver',
        ],
        [
            'name' => 'SAEPUL BAHRI',
            'email' => 'saepulbahri@gmail.com',
            'password' => Hash::make('rahasia123'),
            'birth_place' => 'SURABAYA',
            'sex' => 'M',
            'birth_date' => '29/11/1997',
            'status' => 'Kontrak',
            'join_date' => '01/07/2024',
            'dept' => 'Pengiriman',
            'job_title' => 'Driver',
        ],
        [
            'name' => 'EDI WAHYUDIN',
            'email' => 'ediwahyudin@gmail.com',
            'password' => Hash::make('rahasia123'),
            'birth_place' => 'SIDOARJO',
            'sex' => 'M',
            'birth_date' => '17/07/1998',
            'status' => 'Kontrak',
            'join_date' => '01/07/2024',
            'dept' => 'Pengiriman',
            'job_title' => 'Driver',
        ],
        [
            'name' => 'ARPAN',
            'email' => 'arpan@gmail.com',
            'password' => Hash::make('rahasia123'),
            'birth_place' => 'SURABAYA',
            'sex' => 'M',
            'birth_date' => '03/10/1995',
            'status' => 'Tetap',
            'join_date' => '09/09/2017',
            'dept' => 'Pengiriman',
            'job_title' => 'Driver',
        ],
        [
            'name' => 'YOGI BACHTIAR',
            'email' => 'yogibachtiar@gmail.com',
            'password' => Hash::make('rahasia123'),
            'birth_place' => 'SURABAYA',
            'sex' => 'M',
            'birth_date' => '26/10/1997',
            'status' => 'Tetap',
            'join_date' => '25/09/2018',
            'dept' => 'Pengiriman',
            'job_title' => 'Driver',
        ],
        [
            'name' => 'ASEP SUHERMAN',
            'email' => 'asepsuherman@gmail.com',
            'password' => Hash::make('rahasia123'),
            'birth_place' => 'SIDOARJO',
            'sex' => 'M',
            'birth_date' => '29/05/1997',
            'status' => 'Tetap',
            'join_date' => '06/10/2021',
            'dept' => 'Pengiriman',
            'job_title' => 'Supervisor',
        ],
        [
            'name' => 'AGUSTINUS ARI WIBOWO',
            'email' => 'agustinusariwibowo@gmail.com',
            'password' => Hash::make('rahasia123'),
            'birth_place' => 'BANYUWANGI',
                'sex' => 'M',
                'birth_date' => '15/08/1990',
                'status' => 'Tetap',
                'join_date' => '15/12/2021',
                'dept' => 'Pengiriman',
                'job_title' => 'Manager',
            ],
            [
                'name' => 'FIKRI NURUL HAKIM',
                'email' => 'fikrinurulhakim@gmail.com',
                'password' => Hash::make('rahasia123'),
                'birth_place' => 'MALANG',
                'sex' => 'M',
                'birth_date' => '12/04/1998',
                'status' => 'Tetap',
                'join_date' => '01/09/2020',
                'dept' => 'Admin',
                'job_title' => 'Admin',
            ],
            [
                'name' => 'NINA SUSANTI',
                'email' => 'ninasusanti@gmail.com',
                'password' => Hash::make('rahasia123'),
                'birth_place' => 'SURABAYA',
                'sex' => 'F',
                'birth_date' => '09/09/1997',
                'status' => 'Kontrak',
                'join_date' => '20/07/2023',
                'dept' => 'Keuangan',
                'job_title' => 'Staff',
            ],
            [
                'name' => 'RIZKY MAULANA',
                'email' => 'rizkymaulana@gmail.com',
                'password' => Hash::make('rahasia123'),
                'birth_place' => 'MALANG',
                'sex' => 'M',
                'birth_date' => '05/06/1995',
                'status' => 'Tetap',
                'join_date' => '17/02/2020',
                'dept' => 'Keuangan',
                'job_title' => 'Manager',
            ],
            [
                'name' => 'DEWI LESTARI',
                'email' => 'dewilestari@gmail.com',
                'password' => Hash::make('rahasia123'),
                'birth_place' => 'BANYUWANGI',
                'sex' => 'F',
                'birth_date' => '14/11/1997',
                'status' => 'Tetap',
                'join_date' => '09/03/2023',
                'dept' => 'Keuangan',
                'job_title' => 'Staff',
            ],
            [
                'name' => 'AAN GUSTAVIAN',
                'email' => 'aangustavian@gmail.com',
                'password' => Hash::make('rahasia123'),
                'birth_place' => 'SIDOARJO',
                'sex' => 'M',
                'birth_date' => '18/05/1998',
                'status' => 'Kontrak',
                'join_date' => '01/07/2023',
                'dept' => 'Admin',
                'job_title' => 'Staff',
            ],
            [
                'name' => 'MARTHA MEI',
                'email' => 'marthamei@gmail.com',
                'password' => Hash::make('rahasia123'),
                'birth_place' => 'SURABAYA',
                'sex' => 'F',
                'birth_date' => '20/12/1995',
                'status' => 'Tetap',
                'join_date' => '12/01/2022',
                'dept' => 'IT',
                'job_title' => 'Web Developer',
            ],
            [
                'name' => 'NURUL HIKMAH',
                'email' => 'nurulhikmah@gmail.com',
                'password' => Hash::make('rahasia123'),
                'birth_place' => 'JEMBER',
                'sex' => 'F',
                'birth_date' => '27/09/1996',
                'status' => 'Tetap',
                'join_date' => '04/03/2021',
                'dept' => 'IT',
                'job_title' => 'Web Developer',
            ],
            [
                'name' => 'AGUNG WAHYUDI',
                'email' => 'agungwahyudi@gmail.com',
                'password' => Hash::make('rahasia123'),
                'birth_place' => 'MALANG',
                'sex' => 'M',
                'birth_date' => '30/01/1997',
                'status' => 'Kontrak',
                'join_date' => '21/08/2023',
                'dept' => 'IT',
                'job_title' => 'IT Support',
            ],
            [
                'name' => 'PUTRI WULAN',
                'email' => 'putriwulan@gmail.com',
                'password' => Hash::make('rahasia123'),
                'birth_place' => 'SURABAYA',
                'sex' => 'F',
                'birth_date' => '22/02/1996',
                'status' => 'Tetap',
                'join_date' => '10/01/2020',
                'dept' => 'IT',
                'job_title' => 'Designer',
            ],
        ]);
    }
}
