<?php

namespace Database\Seeders;

use App\Models\User;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Database\Seeder;

class DatabaseSeeder extends Seeder
{
  /**
   * Seed the application's database.
   */
  public function run(): void
  {
    DB::table('users')->insert([
      [
        'name' => 'ANGGA MEI DIANTO',
        'email' => 'anggameidianto@gmail.com',
        'password' => Hash::make('rahasia123'),
        'birth_place' => 'KEDIRI',
        'sex' => 'M',
        'birth_date' => '1997-03-31',
        'status' => 'Kontrak',
        'join_date' => '2024-03-01',
        'dept' => 'Depo Surabaya',
        'job_title' => 'Kepala Depo',
      ],
      [
        'name' => 'DADANG SETIAWAN',
        'email' => 'dadangsetiawan@gmail.com',
        'password' => Hash::make('rahasia123'),
        'birth_place' => 'SURABAYA',
        'sex' => 'M',
        'birth_date' => '1997-11-25',
        'status' => 'Tetap',
        'join_date' => '2023-08-01',
        'dept' => 'Marketing',
        'job_title' => 'Manager',
      ],
      [
        'name' => 'DANIEL TATO ALIK',
        'email' => 'danieltatoalik@gmail.com',
        'password' => Hash::make('rahasia123'),
        'birth_place' => 'SURABAYA',
        'sex' => 'M',
        'birth_date' => '1996-05-19',
        'status' => 'Tetap',
        'join_date' => '2019-11-01',
        'dept' => 'sales',
        'job_title' => 'Sales Rep',
      ],
      [
        'name' => 'RISKY SCORFANIE',
        'email' => 'riskyscorfanie@gmail.com',
        'password' => Hash::make('rahasia123'),
        'birth_place' => 'MALANG',
        'sex' => 'M',
        'birth_date' => '1998-04-23',
        'status' => 'Tetap',
        'join_date' => '2019-01-06',
        'dept' => 'sales',
        'job_title' => 'Supervisor',
      ],
      [
        'name' => 'RIZKY PRASTIKA',
        'email' => 'rizkyprastika@gmail.com',
        'password' => Hash::make('rahasia123'),
        'birth_place' => 'JEMBER',
        'sex' => 'M',
        'birth_date' => '1996-04-24',
        'status' => 'Tetap',
        'join_date' => '2023-01-09',
        'dept' => 'sales',
        'job_title' => 'Sales Rep',
      ],
      [
        'name' => 'SARAH HUSNUL KHOTIMAH',
        'email' => 'sarahhusnulkhotimah@gmail.com',
        'password' => Hash::make('rahasia123'),
        'birth_place' => 'BANYUWANGI',
        'sex' => 'F',
        'birth_date' => '1997-10-26',
        'status' => 'Tetap',
        'join_date' => '2021-01-10',
        'dept' => 'sales',
        'job_title' => 'Sales Rep',
      ],
      [
        'name' => 'DENDI SUPARDI IRAWAN',
        'email' => 'dendisupardiirawan@gmail.com',
        'password' => Hash::make('rahasia123'),
        'birth_place' => 'BANYUWANGI',
        'sex' => 'M',
        'birth_date' => '1997-08-21',
        'status' => 'Tetap',
        'join_date' => '2024-08-09',
        'dept' => 'sales',
        'job_title' => 'Sales Rep',
      ],
      [
        'name' => 'TIRA ASTRIYANI',
        'email' => 'tiraastriyani@gmail.com',
        'password' => Hash::make('rahasia123'),
        'birth_place' => 'BANYUWANGI',
        'sex' => 'F',
        'birth_date' => '1996-07-07',
        'status' => 'Tetap',
        'join_date' => '2024-03-18',
        'dept' => 'sales',
        'job_title' => 'Sales Rep',
      ],
      [
        'name' => 'HARDINTIA W.S',
        'email' => 'hardintiaws@gmail.com',
        'password' => Hash::make('rahasia123'),
        'birth_place' => 'BANYUWANGI',
        'sex' => 'M',
        'birth_date' => '1998-02-25',
        'status' => 'Tetap',
        'join_date' => '2017-09-01',
        'dept' => 'sales',
        'job_title' => 'Sales Rep',
      ],
      [
        'name' => 'DEDE SUHENDRI',
        'email' => 'dedesuhendri@gmail.com',
        'password' => Hash::make('rahasia123'),
        'birth_place' => 'SIDOARJO',
        'sex' => 'M',
        'birth_date' => '1998-05-14',
        'status' => 'Tetap',
        'join_date' => '2017-09-01',
        'dept' => 'Pengiriman',
        'job_title' => 'Driver',
      ],
      [
        'name' => 'RIAN PRASETYO',
        'email' => 'rianprasetyo@gmail.com',
        'password' => Hash::make('rahasia123'),
        'birth_place' => 'SURABAYA',
        'sex' => 'M',
        'birth_date' => '1995-05-16',
        'status' => 'Tetap',
        'join_date' => '2017-09-04',
        'dept' => 'Pengiriman',
        'job_title' => 'Driver',
      ],
      [
        'name' => 'SAEPUL BAHRI',
        'email' => 'saepulbahri@gmail.com',
        'password' => Hash::make('rahasia123'),
        'birth_place' => 'SURABAYA',
        'sex' => 'M',
        'birth_date' => '1997-11-29',
        'status' => 'Kontrak',
        'join_date' => '2024-07-01',
        'dept' => 'Pengiriman',
        'job_title' => 'Driver',
      ],
      [
        'name' => 'EDI WAHYUDIN',
        'email' => 'ediwahyudin@gmail.com',
        'password' => Hash::make('rahasia123'),
        'birth_place' => 'SIDOARJO',
        'sex' => 'M',
        'birth_date' => '1998-07-17',
        'status' => 'Kontrak',
        'join_date' => '2024-07-01',
        'dept' => 'Pengiriman',
        'job_title' => 'Driver',
      ],
      [
        'name' => 'ARPAN',
        'email' => 'arpan@gmail.com',
        'password' => Hash::make('rahasia123'),
        'birth_place' => 'SURABAYA',
        'sex' => 'M',
        'birth_date' => '1995-10-03',
        'status' => 'Tetap',
        'join_date' => '2017-09-09',
        'dept' => 'Pengiriman',
        'job_title' => 'Driver',
      ],
      [
        'name' => 'YOGI BACHTIAR',
        'email' => 'yogibachtiar@gmail.com',
        'password' => Hash::make('rahasia123'),
        'birth_place' => 'SURABAYA',
        'sex' => 'M',
        'birth_date' => '1997-10-26',
        'status' => 'Tetap',
        'join_date' => '2018-09-25',
        'dept' => 'Pengiriman',
        'job_title' => 'Driver',
      ],
      [
        'name' => 'ASEP SUHERMAN',
        'email' => 'asepsuherman@gmail.com',
        'password' => Hash::make('rahasia123'),
        'birth_place' => 'SIDOARJO',
        'sex' => 'M',
        'birth_date' => '1997-05-29',
        'status' => 'Tetap',
        'join_date' => '2021-10-06',
        'dept' => 'Pengiriman',
        'job_title' => 'Supervisor',
      ],
      [
        'name' => 'AGUSTINUS ARI WIBOWO',
        'email' => 'agustinusariwibowo@gmail.com',
        'password' => Hash::make('rahasia123'),
        'birth_place' => 'BANYUWANGI',
        'sex' => 'M',
        'birth_date' => '1990-08-15',
        'status' => 'Tetap',
        'join_date' => '2021-12-15',
        'dept' => 'Pengiriman',
        'job_title' => 'Manager',
      ],
      [
        'name' => 'FIKRI NURUL HAKIM',
        'email' => 'fikrinurulhakim@gmail.com',
        'password' => Hash::make('rahasia123'),
        'birth_place' => 'MALANG',
        'sex' => 'M',
        'birth_date' => '1998-04-12',
        'status' => 'Tetap',
        'join_date' => '2020-09-01',
        'dept' => 'Admin',
        'job_title' => 'Admin',
      ],
      [
        'name' => 'NINA SUSANTI',
        'email' => 'ninasusanti@gmail.com',
        'password' => Hash::make('rahasia123'),
        'birth_place' => 'SURABAYA',
        'sex' => 'F',
        'birth_date' => '1997-09-09',
        'status' => 'Kontrak',
        'join_date' => '2023-07-20',
        'dept' => 'Keuangan',
        'job_title' => 'Staff',
      ],
      [
        'name' => 'RIZKY MAULANA',
        'email' => 'rizkymaulana@gmail.com',
        'password' => Hash::make('rahasia123'),
        'birth_place' => 'MALANG',
        'sex' => 'M',
        'birth_date' => '1995-06-05',
        'status' => 'Tetap',
        'join_date' => '2020-02-17',
        'dept' => 'Keuangan',
        'job_title' => 'Manager',
      ],
      [
        'name' => 'DEWI LESTARI',
        'email' => 'dewilestari@gmail.com',
        'password' => Hash::make('rahasia123'),
        'birth_place' => 'BANYUWANGI',
        'sex' => 'F',
        'birth_date' => '1997-11-14',
        'status' => 'Tetap',
        'join_date' => '2023-03-09',
        'dept' => 'Keuangan',
        'job_title' => 'Staff',
      ],
      [
        'name' => 'AAN GUSTAVIAN',
        'email' => 'aangustavian@gmail.com',
        'password' => Hash::make('rahasia123'),
        'birth_place' => 'SIDOARJO',
        'sex' => 'M',
        'birth_date' => '1998-05-18',
        'status' => 'Kontrak',
        'join_date' => '2023-07-01',
        'dept' => 'Admin',
        'job_title' => 'Staff',
      ],
      [
        'name' => 'MARTHA MEI',
        'email' => 'marthamei@gmail.com',
        'password' => Hash::make('rahasia123'),
        'birth_place' => 'SURABAYA',
        'sex' => 'F',
        'birth_date' => '1995-12-20',
        'status' => 'Tetap',
        'join_date' => '2022-01-12',
        'dept' => 'IT',
        'job_title' => 'Web Developer',
      ],
      [
        'name' => 'NURUL HIKMAH',
        'email' => 'nurulhikmah@gmail.com',
        'password' => Hash::make('rahasia123'),
        'birth_place' => 'JEMBER',
        'sex' => 'F',
        'birth_date' => '1996-09-27',
        'status' => 'Tetap',
        'join_date' => '2021-03-04',
        'dept' => 'IT',
        'job_title' => 'Web Developer',
      ],
      [
        'name' => 'AGUNG WAHYUDI',
        'email' => 'agungwahyudi@gmail.com',
        'password' => Hash::make('rahasia123'),
        'birth_place' => 'MALANG',
        'sex' => 'M',
        'birth_date' => '1997-01-30',
        'status' => 'Kontrak',
        'join_date' => '2023-08-21',
        'dept' => 'IT',
        'job_title' => 'IT Support',
      ],
      [
        'name' => 'PUTRI WULAN',
        'email' => 'putriwulan@gmail.com',
        'password' => Hash::make('rahasia123'),
        'birth_place' => 'SURABAYA',
        'sex' => 'F',
        'birth_date' => '1996-02-22',
        'status' => 'Tetap',
        'join_date' => '2020-01-10',
        'dept' => 'IT',
        'job_title' => 'Designer',
      ],
    ]);
  }
}
